server:
  port: 8888
spring:
  profiles:
    include: db,app
    active: dev
  cache:
    type: caffeine
    cache-names:
      - user
      - person
    caffeine:
      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=10s,refreshAfterWrite=5s
  thymeleaf:
    cache: false
    content-type: text/html
    mode: HTML5
    encoding: UTF-8
    suffix: .html
    prefix: classpath:/templates/
  application:
    name: springboot-demo
#  设置文件上传配置
#  http:
#    multipart:
#      enabled: true
#      max-file-size: 500MB
#      max-request-size: 500MB
logging:
  config: classpath:logback-spring.xml
#logging:
#  level:
#    root: WARN
#    com:
#      juemuren: DEBUG
#  file: log/server.log #默认情况下，Spring Boot将日志输出到控制台，不会写到日志文件

#springBoot使用thymeleaf配置
#actuator资源配置
management:
  port: 9999
  context-path: /monitor
endpoints:
  shutdown:
    enabled: false
info:
  app:
    name: springBoot-demo-actuator
    version: 1.0
security:
  basic:
    enabled: false

# mybatis分页设置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
eureka:
  client:
    serviceUrl:
      defaultZone: "http://112.74.161.161:8761/eureka/"
    fetch-registry: false
    register-with-eureka: false
zookeeper:
  server:
    host: 112.74.161.161:2181
    sessionTimeout: 5000
    connectionTimeout: 3000


