server:
  port: 8888
spring:
  profiles:
    include: db,app
    active: dev
  cache:
    type: caffeine
    cache-names:
      - user
      - person
    caffeine:
      spec: initialCapacity=50,maximumSize=500,expireAfterWrite=10s,refreshAfterWrite=5s
logging:
  config: classpath:logback-spring.xml
#logging:
#  level:
#    root: WARN
#    com:
#      tuandai: DEBUG
#  file: log/server.log #默认情况下，Spring Boot将日志输出到控制台，不会写到日志文件

#actuator资源配置
management:
  port: 9999
  context-path: /monitor
endpoints:
  shutdown:
    enabled: false
info:
  app:
    name: springBoot-demo-actuator
    version: 1.0
security:
  basic:
    enabled: false

